docker-container: &docker-container
  plugins:
    - automattic/bash-cache#f7c9466a826f8bb3c2863dad60e2882f679e0a74
    - docker#v3.8.0:
        image: "public.ecr.aws/automattic/android-build-image:311ab824e9fd33ebb71de83c3fd1c328ea84443b"
        environment:
          - "CI=true"
          - "PATH=/var/lib/buildkite-agent/plugins/library_plugin_binaries:${PATH}"
        # volumes:
        #   - "/var/lib/buildkite-agent/plugins:/var/lib/buildkite-agent/plugins"

steps:
  - label: "checkstyle"
    <<: *docker-container
    command: |
      echo "--- 🧹 Linting"
      echo "buildkite-agent"
      ls /var/lib/buildkite-agent

      echo "buildkite-agent/plugin"
      ls /var/lib/buildkite-agent/plugins

      echo "updating path"
      $PATH="$PATH:/var/lib/buildkite-agent/plugins/library_plugin_binaries"

      # echo $PATH
      which restore_cache
      cp gradle.properties-example gradle.properties
      ./gradlew checkstyle
    artifact_paths:
      - "**/build/reports/checkstyle/checkstyle.*"

  - label: "detekt"
    <<: *docker-container
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew detektAll
    artifact_paths:
      - "**/build/reports/detekt/detekt.html"

  - label: "lint"
    <<: *docker-container
    command: |
      echo "--- 🧹 Linting"
      cp gradle.properties-example gradle.properties
      ./gradlew lintVanillaRelease
    artifact_paths:
      - "**/build/reports/lint-results*.*"

  - label: "Test WooCommerce"
    <<: *docker-container
    command: |
      echo "--- 🧪 Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew testVanillaRelease

  - label: "Test CardReaderModule"
    <<: *docker-container
    command: |
      echo "--- 🧪 Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew lib:cardreader:testRelease

  - label: "Ensure Screenshot Tests Build"
    <<: *docker-container
    command: |
      echo "--- ⚒️ Building"
      cp gradle.properties-example gradle.properties
      ./gradlew assembleVanillaDebugAndroidTest